# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b8d0b0e37c73c0a070288713f3f217a9daa6f9a621fa67adb24b9a6550f78a3b0e0c398983a38addb9fef96bb2c8f480a4c09ba7f5ee9f17db3c0fef1f68695

test:
  secret_key_base: e5cafec8b294e1a2003049eb8a987f9b23e5796ab957e6b54665ebc03a36dd4e232d6427f54a0c1b4a0519c9895bc0c307eef50f88b58330f30a9722d8113a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
